
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-15T18:13:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5db1deb7d03094ba6383dbbd9984802b902f2a14",
 "version": "1.0.59"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
