# Generated by Django 3.2.13 on 2022-06-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buelleten', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='display',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='display',
            name='profile',
            field=models.CharField(choices=[('impressive', 'Impressive based PDF/image/video display'), ('surf', 'Website display based on surf browser')], default='impressive', max_length=10, verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='display',
            name='display_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='buelleten.displaygroup', verbose_name='Display group'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='display_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='buelleten.displaygroup', verbose_name='Display group'),
        ),
    ]
