# Generated by Django 4.2.3 on 2023-07-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("buelleten", "0002_display_variants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="display",
            options={"verbose_name": "Display", "verbose_name_plural": "Displays"},
        ),
        migrations.AlterModelOptions(
            name="displaygroup",
            options={"verbose_name": "Display Group", "verbose_name_plural": "Display Groups"},
        ),
        migrations.AlterModelOptions(
            name="slide",
            options={
                "ordering": ["order"],
                "verbose_name": "Slide",
                "verbose_name_plural": "Slides",
            },
        ),
        migrations.AlterField(
            model_name="display",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Description"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="slide",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
