# Generated by Django 4.2.3 on 2023-07-22 15:18

import aleksis.core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buelleten', '0003_verbose_names_site_related_name_description_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='managed_by_app_label',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='App label of app responsible for managing this instance'),
        ),
        migrations.AddField(
            model_name='displaygroup',
            name='managed_by_app_label',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='App label of app responsible for managing this instance'),
        ),
    ]
