# Generated by Django 4.2.9 on 2024-01-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buelleten", "0004_add_managed_by_app_label"),
    ]

    operations = ([
        migrations.AlterModelManagers(
            name="display",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="displaygroup",
            managers=[],
        ),
    ] + [
        migrations.RunSQL(
            f"ALTER TABLE buelleten_{model_name} drop column if exists site_id;"
        ) for model_name  in
        [
            "displaygroup",
            "display",
            "slide",
            "foreignurlslide",
            "uploadedfileslide",
            "staticcontentslide",
        ]
    ])
