
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-14T14:54:42-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf7df2fcd060128a9d369f40ef6334c51ee44ccf",
 "version": "2.30.0rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
