
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2024-02-13T12:37:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "784f8d648bde9fa266bd88a8beb29567931e4407",
 "version": "0.23.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
