from .main import get_random_word
from .main import get_random_words
from .Language import Afrikaans
from .Language import Amharic
from .Language import Arabic
from .Language import Armenian
from .Language import Azerbaijani
from .Language import Basque
from .Language import Belarusian
from .Language import Bengali
from .Language import Bosnian
from .Language import Bulgarian
from .Language import Catalan
from .Language import Cebuano
from .Language import Chichewa
from .Language import Chinese
from .Language import Corsican
from .Language import Croatian
from .Language import Czech
from .Language import Danish
from .Language import Dutch
from .Language import English
from .Language import Esperanto
from .Language import Estonian
from .Language import Filipino
from .Language import Finnish
from .Language import French
from .Language import Frisian
from .Language import Galician
from .Language import Georgian
from .Language import German
from .Language import Greek
from .Language import Gujarati
from .Language import HaitianCreole
from .Language import Hausa
from .Language import Hawaiian
from .Language import Hebrew
from .Language import Hindi
from .Language import Hmong
from .Language import Hungarian
from .Language import Icelandic
from .Language import Igbo
from .Language import Indonesian
from .Language import Irish
from .Language import Italian
from .Language import Japanese
from .Language import Javanese
from .Language import Kannada
from .Language import Kazakh
from .Language import Khmer
from .Language import Kinyarwanda
from .Language import Korean
from .Language import Kurdish
from .Language import Kyrgyz
from .Language import Lao
from .Language import Latin
from .Language import Latvian
from .Language import Lithuanian
from .Language import Luxembourgish
from .Language import Macedonian
from .Language import Malagasy
from .Language import Malay
from .Language import Malayalam
from .Language import Maltese
from .Language import Maori
from .Language import Marathi
from .Language import Mongolian
from .Language import Myanmar
from .Language import Nepali
from .Language import Norwegian
from .Language import Odia
from .Language import Pashto
from .Language import Persian
from .Language import Polish
from .Language import Portuguese
from .Language import Punjabi
from .Language import Romanian
from .Language import Russian
from .Language import Samoan
from .Language import ScotsGaelic
from .Language import Serbian
from .Language import Sesotho
from .Language import Shona
from .Language import Sindhi
from .Language import Sinhala
from .Language import Slovak
from .Language import Slovenian
from .Language import Somali
from .Language import Spanish
from .Language import Sundanese
from .Language import Swahili
from .Language import Swedish
from .Language import Tajik
from .Language import Tamil
from .Language import Tatar
from .Language import Telugu
from .Language import Thai
from .Language import Turkish
from .Language import Turkmen
from .Language import Ukranian
from .Language import Urdu
from .Language import Uyghur
from .Language import Uzbek
from .Language import Vietnamese
from .Language import Welsh
from .Language import Xhosa
from .Language import Yiddish
from .Language import Yoruba
from .Language import Zulu
