# Generated by Django 4.2.7 on 2024-02-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evercycle_models', '0006_processorsecurity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='ProcessorDeviceType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('outbound_ship_weight', models.IntegerField()),
                ('return_ship_weight', models.IntegerField()),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evercycle_models.processor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evercycle_models.devicetype')),
            ],
            options={
                'db_table': 'processor_device_type',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'service_order',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderDevice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('disposition_status', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('processor_device_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evercycle_models.processordevicetype')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evercycle_models.serviceorder')),
            ],
            options={
                'db_table': 'service_order_device',
            },
        ),
    ]
