import threading
from .._utils import empty_queue as empty_queue, gen_logger as gen_logger

class LoggerThread(threading.Thread):
    def __init__(self, app_shared) -> None: ...
    def run(self) -> None: ...
    def close(self) -> None: ...
