# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-pil-utils',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-pil-utils',
                'lib_path': 'cjm_pil_utils'},
  'syms': { 'cjm_pil_utils.annotation': { 'cjm_pil_utils.annotation.draw_bboxes': ( 'annotation.html#draw_bboxes',
                                                                                    'cjm_pil_utils/annotation.py'),
                                          'cjm_pil_utils.annotation.draw_masks': ( 'annotation.html#draw_masks',
                                                                                   'cjm_pil_utils/annotation.py')},
            'cjm_pil_utils.core': { 'cjm_pil_utils.core.avg_images': ('core.html#avg_images', 'cjm_pil_utils/core.py'),
                                    'cjm_pil_utils.core.crop_square': ('core.html#crop_square', 'cjm_pil_utils/core.py'),
                                    'cjm_pil_utils.core.get_img_files': ('core.html#get_img_files', 'cjm_pil_utils/core.py'),
                                    'cjm_pil_utils.core.img_save_path': ('core.html#img_save_path', 'cjm_pil_utils/core.py'),
                                    'cjm_pil_utils.core.resize_img': ('core.html#resize_img', 'cjm_pil_utils/core.py'),
                                    'cjm_pil_utils.core.stack_imgs': ('core.html#stack_imgs', 'cjm_pil_utils/core.py')}}}
