#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2401-38-g2e80cb34"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2401
#define NETGEN_VERSION_TWEAK 38
#define NETGEN_VERSION_HASH "g2e80cb34"
#endif // NETGEN_VERSION_HPP_INCLUDED
