import math


class Converter:
    def __init__(self):
        """A class which offers a few methods to convert numbers to a different format."""
        super().__init__()

    def roundnum(self, number: float):
        return round(float(number))

    def formatnum(self, number: float):
        return format((float(number)), ",")

    def tosuffix(self, number: float):
        suffixes = [
            "",
            "K",
            "M",
            "B",
            "T",
            "Qa",
            "Qi",
            "Sx",
            "Sp",
            "Oc",
            "No",
            "Dc",
            "Ud",
            "Dd",
            "Td",
            "Qad",
            "Qid",
            "Sxd",
            "Spd",
            "Ocd",
            "Nod",
            "Vg",
            "Uvg",
            "Dvg",
            "Tvg",
            "Qavg",
            "Qivg",
            "Sxvg",
            "Spvg",
            "Ocvg",
            "Novg",
            "Tg",
            "Utg",
            "Dtg",
            "Ttg",
            "Qatg",
            "Qitg",
            "Sxtg",
            "Sptg",
            "Octg",
            "Notg",
            "Qag",
            "Uqag",
            "Dqag",
            "Tqag",
            "Qaqag",
            "Qiqag",
            "Sxqag",
            "Spqag",
            "Ocqag",
            "Noqag",
            "Qig",
            "Uqig",
            "Dqig",
            "Tqig",
            "Qaqig",
            "Qiqig",
            "Sxqig",
            "Spqig",
            "Ocqig",
            "Noqig",
            "Sxg",
            "Usxg",
            "Dsxg",
            "Tsxg",
            "Qasxg",
            "Qisxg",
            "Sxsxg",
            "Spsxg",
            "Ocsxg",
            "Nosxg",
            "Spg",
            "Uspg",
            "Dspg",
            "Tspg",
            "Qaspg",
            "Qispg",
            "Sxspg",
            "Spspg",
            "Ocspg",
            "Nospg",
            "Ocg",
            "Uocg",
            "Docg",
            "Tocg",
            "Qaocg",
            "Qiocg",
            "Sxocg",
            "Spocg",
            "Ococg",
            "Noocg",
            "Nog",
            "Unog",
            "Dnog",
            "Tnog",
            "Qanog",
            "Qinog",
            "Sxnog",
            "Spnog",
            "Ocnog",
            "Nonog",
            "Ce",
            "Uce",
        ]
        number = float(number)
        if number < 1000:
            return str(number)
        for i in range(len(suffixes)):
            if number < math.pow(10, (i * 3)):
                return (
                    str(math.floor(number / ((math.pow(10, (i - 1) * 3)) / 100)) / 100)
                    + suffixes[i - 1].upper()
                )

    def fromsuffix(self, number: str):
        suffixes = {
            "K": 3,
            "M": 6,
            "B": 9,
            "T": 12,
            "Qa": 15,
            "Qi": 18,
            "Sx": 21,
            "Sp": 24,
            "Oc": 27,
            "No": 30,
            "Dc": 33,
            "Ud": 36,
            "Dd": 39,
            "Td": 42,
            "Qad": 45,
            "Qid": 48,
            "Sxd": 51,
            "Spd": 54,
            "Ocd": 57,
            "Nod": 60,
            "Vg": 63,
            "Uvg": 66,
            "Dvg": 69,
            "Tvg": 72,
            "Qavg": 75,
            "Qivg": 78,
            "Sxvg": 81,
            "Spvg": 84,
            "Ocvg": 87,
            "Novg": 90,
            "Tg": 93,
            "Utg": 96,
            "Dtg": 99,
            "Ttg": 102,
            "Qatg": 105,
            "Qitg": 108,
            "Sxtg": 111,
            "Sptg": 114,
            "Octg": 117,
            "Notg": 120,
            "Qag": 123,
            "Uqag": 126,
            "Dqag": 129,
            "Tqag": 132,
            "Qaqag": 135,
            "Qiqag": 138,
            "Sxqag": 141,
            "Spqag": 144,
            "Ocqag": 147,
            "Noqag": 150,
            "Qig": 153,
            "Uqig": 156,
            "Dqig": 159,
            "Tqig": 162,
            "Qaqig": 165,
            "Qiqig": 168,
            "Sxqig": 171,
            "Spqig": 174,
            "Ocqig": 177,
            "Noqig": 180,
            "Sxg": 183,
            "Usxg": 186,
            "Dsxg": 189,
            "Tsxg": 192,
            "Qasxg": 195,
            "Qisxg": 198,
            "Sxsxg": 201,
            "Spsxg": 204,
            "Ocsxg": 207,
            "Nosxg": 210,
            "Spg": 213,
            "Uspg": 216,
            "Dspg": 219,
            "Tspg": 222,
            "Qaspg": 225,
            "Qispg": 228,
            "Sxspg": 231,
            "Spspg": 234,
            "Ocspg": 237,
            "Nospg": 240,
            "Ocg": 243,
            "Uocg": 246,
            "Docg": 249,
            "Tocg": 252,
            "Qaocg": 255,
            "Qiocg": 258,
            "Sxocg": 261,
            "Spocg": 264,
            "Ococg": 267,
            "Noocg": 270,
            "Nog": 273,
            "Unog": 276,
            "Dnog": 279,
            "Tnog": 282,
            "Qanog": 285,
            "Qinog": 288,
            "Sxnog": 291,
            "Spnog": 294,
            "Ocnog": 297,
            "Nonog": 300,
            "Ce": 303,
            "Uce": 306,
        }

        number = number.upper()

        for suffix, power in suffixes.items():
            if number.endswith(suffix.upper()):
                num_part = number[: -len(suffix)]
                return float(num_part) * math.pow(10, power)

        return float(number)
