
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-12T07:50:11+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "7ff4400965dad67ac7b9e1adfb3db978154a432c",
 "version": "0.0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
