
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-13T17:46:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8c05fb4a86ac9768cdccde9a5993c73ed07e1f1",
 "version": "2.9.10.post0.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
