
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-14T13:26:28-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cc4171b3306816324a0e26b93adf8b94b176813",
 "version": "1.23.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
