# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the Veeroute Studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg)

    The version of the OpenAPI document: 6.20.2252
    Contact: servicedesk@veeroute.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from vrt_lss_studio.models.table_trip_fields import TableTripFields

class TableTrip(BaseModel):
    """
    Trip.  # noqa: E501
    """
    fields: TableTripFields
    elements: Annotated[List[TableTripFields], Field(min_length=0, max_length=15001)] = Field(description="A list.")
    __properties = ["fields", "elements"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TableTrip:
        """Create an instance of TableTrip from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of fields
        if self.fields:
            _dict['fields'] = self.fields.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in elements (list)
        _items = []
        if self.elements:
            for _item in self.elements:
                if _item:
                    _items.append(_item.to_dict())
            _dict['elements'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TableTrip:
        """Create an instance of TableTrip from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TableTrip.parse_obj(obj)

        _obj = TableTrip.parse_obj({
            "fields": TableTripFields.from_dict(obj.get("fields")) if obj.get("fields") is not None else None,
            "elements": [TableTripFields.from_dict(_item) for _item in obj.get("elements")] if obj.get("elements") is not None else None
        })
        return _obj


