# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the Veeroute Studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg)

    The version of the OpenAPI document: 6.20.2252
    Contact: servicedesk@veeroute.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TripStartTimeStrategy(str, Enum):
    """
    The strategy of the choosing optimal trip start time:   * `EARLIEST_FINISH`   * `LOWEST_COST` 
    """

    """
    allowed enum values
    """
    EARLIEST_FINISH = 'EARLIEST_FINISH'
    LOWEST_COST = 'LOWEST_COST'

    @classmethod
    def from_json(cls, json_str: str) -> TripStartTimeStrategy:
        """Create an instance of TripStartTimeStrategy from a JSON string"""
        return TripStartTimeStrategy(json.loads(json_str))


