
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-12T08:16:35+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "db8615967e3d6745c9f7c832e80778cbb2fa0a91",
 "version": "0.7.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
