
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-13T16:35:24-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e753ff576dbe8ca5f963ae82a42f40e5f70aa9eb",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
