# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/management/public_management_router.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from truera.protobuf.public.management import management_service_pb2 as truera_dot_protobuf_dot_public_dot_management_dot_management__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@truera/protobuf/public/management/public_management_router.proto\x12\x06truera\x1a\x1cgoogle/api/annotations.proto\x1a:truera/protobuf/public/management/management_service.proto\"8\n!PublicManagementRouterPingRequest\x12\x13\n\x0btest_string\x18\x01 \x01(\t\"9\n\"PublicManagementRouterPingResponse\x12\x13\n\x0btest_string\x18\x01 \x01(\t2\xba\x04\n\x16PublicManagementRouter\x12\x81\x01\n\x04Ping\x12).truera.PublicManagementRouterPingRequest\x1a*.truera.PublicManagementRouterPingResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/router/ping/{test_string}\x12\xa4\x01\n\x1fTestManagementServiceConnection\x12).truera.PublicManagementRouterPingRequest\x1a*.truera.PublicManagementRouterPingResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/router/ping/mgmtsvc/{test_string}\x12\x62\n\x0fSignUpNewTenant\x12\x1e.truera.SignUpNewTenantRequest\x1a\x17.truera.CreatedUserInfo\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0e/router/signup\x12\x90\x01\n\x1aRetriggerEmailVerification\x12).truera.RetriggerEmailVerificationRequest\x1a*.truera.RetriggerEmailVerificationResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/router/verifyemailB\x7f\n\x1e\x63om.truera.protobuf.managementB\x1bPublicManagementRouterProtoP\x01Z>truera.com/protobuf/public/management/public_management_routerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.management.public_management_router_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.truera.protobuf.managementB\033PublicManagementRouterProtoP\001Z>truera.com/protobuf/public/management/public_management_router'
  _PUBLICMANAGEMENTROUTER.methods_by_name['Ping']._options = None
  _PUBLICMANAGEMENTROUTER.methods_by_name['Ping']._serialized_options = b'\202\323\344\223\002\034\022\032/router/ping/{test_string}'
  _PUBLICMANAGEMENTROUTER.methods_by_name['TestManagementServiceConnection']._options = None
  _PUBLICMANAGEMENTROUTER.methods_by_name['TestManagementServiceConnection']._serialized_options = b'\202\323\344\223\002$\022\"/router/ping/mgmtsvc/{test_string}'
  _PUBLICMANAGEMENTROUTER.methods_by_name['SignUpNewTenant']._options = None
  _PUBLICMANAGEMENTROUTER.methods_by_name['SignUpNewTenant']._serialized_options = b'\202\323\344\223\002\020\"\016/router/signup'
  _PUBLICMANAGEMENTROUTER.methods_by_name['RetriggerEmailVerification']._options = None
  _PUBLICMANAGEMENTROUTER.methods_by_name['RetriggerEmailVerification']._serialized_options = b'\202\323\344\223\002\025\"\023/router/verifyemail'
  _PUBLICMANAGEMENTROUTERPINGREQUEST._serialized_start=166
  _PUBLICMANAGEMENTROUTERPINGREQUEST._serialized_end=222
  _PUBLICMANAGEMENTROUTERPINGRESPONSE._serialized_start=224
  _PUBLICMANAGEMENTROUTERPINGRESPONSE._serialized_end=281
  _PUBLICMANAGEMENTROUTER._serialized_start=284
  _PUBLICMANAGEMENTROUTER._serialized_end=854
# @@protoc_insertion_point(module_scope)
