# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/runner/work/parsec-cloud/parsec-cloud/parsec/core/gui/forms/authentication_choice_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthenticationChoiceWidget(object):
    def setupUi(self, AuthenticationChoiceWidget):
        AuthenticationChoiceWidget.setObjectName("AuthenticationChoiceWidget")
        AuthenticationChoiceWidget.resize(411, 219)
        AuthenticationChoiceWidget.setStyleSheet("#AuthenticationChoiceWidget, #scrollAreaWidgetContents {\n"
"    background-color: #F4F4F4;\n"
"}\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(AuthenticationChoiceWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(AuthenticationChoiceWidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 411, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.combo_auth_method = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.combo_auth_method.setObjectName("combo_auth_method")
        self.verticalLayout_2.addWidget(self.combo_auth_method)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.verticalLayout_3.addLayout(self.main_layout)
        self.verticalLayout_4.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(AuthenticationChoiceWidget)
        QtCore.QMetaObject.connectSlotsByName(AuthenticationChoiceWidget)

    def retranslateUi(self, AuthenticationChoiceWidget):
        _translate = QtCore.QCoreApplication.translate
        AuthenticationChoiceWidget.setWindowTitle(_translate("AuthenticationChoiceWidget", "Form"))
        self.label.setText(_translate("AuthenticationChoiceWidget", "TEXT_AUTHENTICATION_METHOD_CHOICE"))
