# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backlight_slider.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BackLightSlider(object):
    def setupUi(self, BackLightSlider):
        BackLightSlider.setObjectName("BackLightSlider")
        BackLightSlider.resize(298, 86)
        self.verticalLayout = QtWidgets.QVBoxLayout(BackLightSlider)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.brightness_label = QtWidgets.QLabel(BackLightSlider)
        self.brightness_label.setObjectName("brightness_label")
        self.horizontalLayout.addWidget(self.brightness_label)
        self.value_label = QtWidgets.QLabel(BackLightSlider)
        self.value_label.setObjectName("value_label")
        self.horizontalLayout.addWidget(self.value_label)
        self.folder_label = QtWidgets.QLabel(BackLightSlider)
        self.folder_label.setObjectName("folder_label")
        self.horizontalLayout.addWidget(self.folder_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalSlider = QtWidgets.QSlider(BackLightSlider)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(BackLightSlider)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(BackLightSlider)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(BackLightSlider)
        QtCore.QMetaObject.connectSlotsByName(BackLightSlider)

    def retranslateUi(self, BackLightSlider):
        _translate = QtCore.QCoreApplication.translate
        BackLightSlider.setWindowTitle(_translate("BackLightSlider", "Form"))
        self.brightness_label.setText(_translate("BackLightSlider", "Brightness: "))
        self.value_label.setText(_translate("BackLightSlider", "0"))
        self.folder_label.setText(_translate("BackLightSlider", "Driver_0"))
        self.label.setText(_translate("BackLightSlider", "0"))
        self.label_2.setText(_translate("BackLightSlider", "100"))
