# coding: utf-8

"""
    VRt.Account [AC]

    # Description  Veeroute Account Panel.  ## Entity relationship diagram  ![erd](../uml/account.svg) 

    The version of the OpenAPI document: 6.20.2252
    Contact: servicedesk@veeroute.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FlowType(str, Enum):
    """
    Data flow type.
    """

    """
    allowed enum values
    """
    INPUT = 'INPUT'
    OUTPUT = 'OUTPUT'

    @classmethod
    def from_json(cls, json_str: str) -> FlowType:
        """Create an instance of FlowType from a JSON string"""
        return FlowType(json.loads(json_str))


