
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-12T18:12:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6a3ab41267a2ea9224a0158eeed67efbc4e5b5a",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
