# Autogenerated by devscripts/update-version.py

__version__ = '2024.02.14.232704'

RELEASE_GIT_HEAD = 'fb44020fa98e47620b3aa1dab94b4c5b7bfb40bd'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.02.14.232704dev'
