
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-12T17:00:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9066085e351bed9942788e1327bd135867d60f60",
 "version": "0.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
