# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/project/parsec/core/gui/forms/device_recovery_export_page2_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeviceRecoveryExportPage2Widget(object):
    def setupUi(self, DeviceRecoveryExportPage2Widget):
        DeviceRecoveryExportPage2Widget.setObjectName("DeviceRecoveryExportPage2Widget")
        DeviceRecoveryExportPage2Widget.resize(479, 311)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeviceRecoveryExportPage2Widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DeviceRecoveryExportPage2Widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(DeviceRecoveryExportPage2Widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_file_path = ClickableLabel(DeviceRecoveryExportPage2Widget)
        self.label_file_path.setText("")
        self.label_file_path.setObjectName("label_file_path")
        self.horizontalLayout_3.addWidget(self.label_file_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(DeviceRecoveryExportPage2Widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.edit_passphrase = QtWidgets.QTextEdit(DeviceRecoveryExportPage2Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_passphrase.sizePolicy().hasHeightForWidth())
        self.edit_passphrase.setSizePolicy(sizePolicy)
        self.edit_passphrase.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_passphrase.setFont(font)
        self.edit_passphrase.setFrameShape(QtWidgets.QFrame.Box)
        self.edit_passphrase.setFrameShadow(QtWidgets.QFrame.Plain)
        self.edit_passphrase.setUndoRedoEnabled(False)
        self.edit_passphrase.setReadOnly(True)
        self.edit_passphrase.setAcceptRichText(False)
        self.edit_passphrase.setObjectName("edit_passphrase")
        self.horizontalLayout_4.addWidget(self.edit_passphrase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_print = QtWidgets.QPushButton(DeviceRecoveryExportPage2Widget)
        self.button_print.setObjectName("button_print")
        self.horizontalLayout_2.addWidget(self.button_print)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(DeviceRecoveryExportPage2Widget)
        QtCore.QMetaObject.connectSlotsByName(DeviceRecoveryExportPage2Widget)

    def retranslateUi(self, DeviceRecoveryExportPage2Widget):
        _translate = QtCore.QCoreApplication.translate
        DeviceRecoveryExportPage2Widget.setWindowTitle(_translate("DeviceRecoveryExportPage2Widget", "Form"))
        self.label.setText(_translate("DeviceRecoveryExportPage2Widget", "TEXT_RECOVERY_EXPORT_KEEP_INFO_INSTRUCTIONS"))
        self.label_2.setText(_translate("DeviceRecoveryExportPage2Widget", "TEXT_RECOVERY_EXPORT_FILE_PATH_LABEL"))
        self.label_4.setText(_translate("DeviceRecoveryExportPage2Widget", "TEXT_RECOVERY_EXPORT_KEY_LABEL"))
        self.button_print.setText(_translate("DeviceRecoveryExportPage2Widget", "ACTION_PRINT_RECOVERY_KEY"))
from parsec.core.gui.custom_widgets import ClickableLabel
