# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/project/parsec/core/gui/forms/password_authentication_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordAuthenticationWidget(object):
    def setupUi(self, PasswordAuthenticationWidget):
        PasswordAuthenticationWidget.setObjectName("PasswordAuthenticationWidget")
        PasswordAuthenticationWidget.resize(400, 210)
        PasswordAuthenticationWidget.setMinimumSize(QtCore.QSize(0, 210))
        PasswordAuthenticationWidget.setStyleSheet("#label_mismatch {\n"
"    color: #F1962B;\n"
"}\n"
"\n"
"#label_password_warning {\n"
"    color: #F1962B;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(PasswordAuthenticationWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_password_warning = QtWidgets.QLabel(PasswordAuthenticationWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_password_warning.setFont(font)
        self.label_password_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.label_password_warning.setWordWrap(True)
        self.label_password_warning.setObjectName("label_password_warning")
        self.verticalLayout.addWidget(self.label_password_warning)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_password = QtWidgets.QLabel(PasswordAuthenticationWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.verticalLayout_14.addWidget(self.label_password)
        self.line_edit_password = QtWidgets.QLineEdit(PasswordAuthenticationWidget)
        self.line_edit_password.setMinimumSize(QtCore.QSize(0, 0))
        self.line_edit_password.setText("")
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setPlaceholderText("")
        self.line_edit_password.setObjectName("line_edit_password")
        self.verticalLayout_14.addWidget(self.line_edit_password)
        self.verticalLayout.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_confirmation = QtWidgets.QLabel(PasswordAuthenticationWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_confirmation.setFont(font)
        self.label_confirmation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_confirmation.setObjectName("label_confirmation")
        self.verticalLayout_15.addWidget(self.label_confirmation)
        self.line_edit_password_check = QtWidgets.QLineEdit(PasswordAuthenticationWidget)
        self.line_edit_password_check.setMinimumSize(QtCore.QSize(0, 0))
        self.line_edit_password_check.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password_check.setPlaceholderText("")
        self.line_edit_password_check.setObjectName("line_edit_password_check")
        self.verticalLayout_15.addWidget(self.line_edit_password_check)
        self.label_mismatch = QtWidgets.QLabel(PasswordAuthenticationWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_mismatch.setFont(font)
        self.label_mismatch.setWordWrap(True)
        self.label_mismatch.setObjectName("label_mismatch")
        self.verticalLayout_15.addWidget(self.label_mismatch)
        self.verticalLayout.addLayout(self.verticalLayout_15)
        self.layout_password_strength = QtWidgets.QHBoxLayout()
        self.layout_password_strength.setObjectName("layout_password_strength")
        self.verticalLayout.addLayout(self.layout_password_strength)

        self.retranslateUi(PasswordAuthenticationWidget)
        QtCore.QMetaObject.connectSlotsByName(PasswordAuthenticationWidget)

    def retranslateUi(self, PasswordAuthenticationWidget):
        _translate = QtCore.QCoreApplication.translate
        PasswordAuthenticationWidget.setWindowTitle(_translate("PasswordAuthenticationWidget", "Form"))
        self.label_password_warning.setText(_translate("PasswordAuthenticationWidget", "TEXT_PASSWORD_WARNING"))
        self.label_password.setText(_translate("PasswordAuthenticationWidget", "TEXT_LABEL_PASSWORD"))
        self.label_confirmation.setText(_translate("PasswordAuthenticationWidget", "TEXT_LABEL_PASSWORD_CONFIRMATION"))
        self.label_mismatch.setText(_translate("PasswordAuthenticationWidget", "TEXT_PASSWORD_CHOICE_MISMATCH"))
