# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/project/parsec/core/gui/forms/qrcode_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QRCodeWidget(object):
    def setupUi(self, QRCodeWidget):
        QRCodeWidget.setObjectName("QRCodeWidget")
        QRCodeWidget.resize(216, 177)
        self.verticalLayout = QtWidgets.QVBoxLayout(QRCodeWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_qrcode = OverlayLabel(QRCodeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_qrcode.sizePolicy().hasHeightForWidth())
        self.label_qrcode.setSizePolicy(sizePolicy)
        self.label_qrcode.setText("")
        self.label_qrcode.setScaledContents(True)
        self.label_qrcode.setObjectName("label_qrcode")
        self.horizontalLayout.addWidget(self.label_qrcode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_text = QtWidgets.QLabel(QRCodeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text.sizePolicy().hasHeightForWidth())
        self.label_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_text.setFont(font)
        self.label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text.setWordWrap(True)
        self.label_text.setObjectName("label_text")
        self.verticalLayout.addWidget(self.label_text)

        self.retranslateUi(QRCodeWidget)
        QtCore.QMetaObject.connectSlotsByName(QRCodeWidget)

    def retranslateUi(self, QRCodeWidget):
        _translate = QtCore.QCoreApplication.translate
        QRCodeWidget.setWindowTitle(_translate("QRCodeWidget", "Form"))
        self.label_text.setText(_translate("QRCodeWidget", "TEXT_CLICK_TO_ENLARGE"))
from parsec.core.gui.custom_widgets import OverlayLabel
