# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/project/parsec/core/gui/forms/search_user_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchUserWidget(object):
    def setupUi(self, SearchUserWidget):
        SearchUserWidget.setObjectName("SearchUserWidget")
        SearchUserWidget.resize(492, 168)
        SearchUserWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SearchUserWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(SearchUserWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_search = QtWidgets.QLineEdit(SearchUserWidget)
        self.line_search.setObjectName("line_search")
        self.horizontalLayout.addWidget(self.line_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_not_found = QtWidgets.QLabel(SearchUserWidget)
        self.label_not_found.setObjectName("label_not_found")
        self.verticalLayout_2.addWidget(self.label_not_found)
        self.user_list_scroll = QtWidgets.QScrollArea(SearchUserWidget)
        self.user_list_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.user_list_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.user_list_scroll.setLineWidth(0)
        self.user_list_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.user_list_scroll.setWidgetResizable(True)
        self.user_list_scroll.setObjectName("user_list_scroll")
        self.user_list = QtWidgets.QWidget()
        self.user_list.setGeometry(QtCore.QRect(0, 0, 492, 66))
        self.user_list.setObjectName("user_list")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.user_list)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_list_scroll.setWidget(self.user_list)
        self.verticalLayout_2.addWidget(self.user_list_scroll)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(SearchUserWidget)
        QtCore.QMetaObject.connectSlotsByName(SearchUserWidget)

    def retranslateUi(self, SearchUserWidget):
        _translate = QtCore.QCoreApplication.translate
        SearchUserWidget.setWindowTitle(_translate("SearchUserWidget", "Form"))
        self.label.setText(_translate("SearchUserWidget", "TEXT_SEARCH_USER"))
        self.line_search.setPlaceholderText(_translate("SearchUserWidget", "TEXT_SEARCH_USER_PLACEHOLDER"))
        self.label_not_found.setText(_translate("SearchUserWidget", "TEXT_NO_MATCHING_USER_FOUND"))
