# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/project/parsec/core/gui/forms/select_user_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectUserWidget(object):
    def setupUi(self, SelectUserWidget):
        SelectUserWidget.setObjectName("SelectUserWidget")
        SelectUserWidget.resize(628, 32)
        SelectUserWidget.setMaximumSize(QtCore.QSize(16777215, 32))
        self.horizontalLayout = QtWidgets.QHBoxLayout(SelectUserWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_name = QtWidgets.QLabel(SelectUserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setText("")
        self.label_name.setObjectName("label_name")
        self.horizontalLayout.addWidget(self.label_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_profile = QtWidgets.QLabel(SelectUserWidget)
        self.label_profile.setText("")
        self.label_profile.setObjectName("label_profile")
        self.horizontalLayout.addWidget(self.label_profile)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_select = Button(SelectUserWidget)
        self.button_select.setProperty("color", QtGui.QColor(0, 146, 255))
        self.button_select.setObjectName("button_select")
        self.horizontalLayout.addWidget(self.button_select)

        self.retranslateUi(SelectUserWidget)
        QtCore.QMetaObject.connectSlotsByName(SelectUserWidget)

    def retranslateUi(self, SelectUserWidget):
        _translate = QtCore.QCoreApplication.translate
        SelectUserWidget.setWindowTitle(_translate("SelectUserWidget", "Form"))
        self.button_select.setText(_translate("SelectUserWidget", "ACTION_SELECT"))
from parsec.core.gui.custom_widgets import Button
