
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-13T20:39:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a419623b437ffbdb10c704b27029b7b3af3de80",
 "version": "2.9.10.post0.dev13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
